stages: 
  - test

cache:
  paths:
    - node_modules/  

test:
  stage: test    
  image: beevelop/nodejs-python
  variables:
    DB_PORT: 3001
    DB_URL: "mongodb:mongo/meatapi"
  services:
    - mongo
  script: 
    - npm i
    - npm test